### ISSUE TITLE
1.2.0 doesn't compile: uses tokio::fs in lib.rs while Cargo.toml doesn't adds tokio dependency feature flag "fs"

### ISSUE THREAD

**Issue by static-cat** [baoyachi/sha256-rs#15]
tokio::fs usage
https://github.com/baoyachi/sha256-rs/blame/d8b1d88996c65c40ca5aff5cd22a3c31b2409692/src/lib.rs#L218

Cargo.toml
https://github.com/baoyachi/sha256-rs/blob/d8b1d88996c65c40ca5aff5cd22a3c31b2409692/Cargo.toml#L20C43-L20C52

**Comment by baoyachi** [comment]
Thx for your report. So funning that the github action was not detected.

**Comment by iddm** [comment]
Please, upload the new version of this crate.
