### ISSUE TITLE
Why is `try_digest` deprecated in `v1.2`? 

### ISSUE THREAD

**Issue by Mossaka** [baoyachi/sha256-rs#17]
Hey there, thank you for contributing and maintaining this crate! 

In the new release of `v1.2` it seems that the `try_digest` function was deprecated. As far as I can tell, this is the only sync function that can return a `Result` type. I think it would be useful to keep this function in the crate so users can choose to use async / sync versions.

**Comment by baoyachi** [comment]
@Mossaka Okay, I will revoke this deprecated declaration in the next version.

**Comment by baoyachi** [comment]
Please use:
```toml
sha256 = "1.2.2"
```

**Comment by Mossaka** [comment]
Thank you! 🙏
