### ISSUE TITLE
Consider moving async methods behind a feature flag

### ISSUE THREAD

**Issue by tosutton** [baoyachi/sha256-rs#18]
The addition of tokio is a breaking change for wasm32 builds. It would be nice to be able to opt out of them.

**Comment by baoyachi** [comment]
I'll think about it.

**Comment by appetrosyan** [comment]
I would strongly consider this. The `async` methods bloat the compiled binary. This is a small thing, but these tend to add up.

**Comment by kailan** [comment]
+1 to this. We have had to pin to `1.1.5` on [Fastly Fiddle](https://developer.fastly.com/learning/tools/fiddle/authoring/#dependencies) for now.

**Comment by baoyachi** [comment]
@tosutton @appetrosyan @kailan 
Update new version, if you don't want use `async` features
```toml
[dependencies]
sha256 = { version = "1.4.0", default-features = false }
```

**Comment by kailan** [comment]
@baoyachi fantastic, thank you so much for the quick resolution!

**Comment by ollpu** [comment]
The `async-trait` dependency could also be made optional by changing
```rs
#[async_trait]
```
to
```rs
#[cfg_attr(feature = "async", async_trait)]
```
