### ISSUE TITLE
Don't load the entire file into memory to hash it

### ISSUE THREAD

**Issue by LoganDark** [baoyachi/sha256-rs#3]
The `hash_file` function could stream the file into the hasher rather than reading the entire file into memory first.

**Comment by baoyachi** [comment]
## Need TODO
- [x] fs::read need support Rust Async
- [x] Refactor code

**Comment by baoyachi** [comment]
Currently,new version published, please use `try_async_digest` function replace of `hash_file ` function.
```toml
sha256 = "1.2.0"
```

**Comment by baoyachi** [comment]
@LoganDark Thx .
