### ISSUE TITLE
Hope to add the license declaration file.

### ISSUE THREAD

**Issue by vincepx** [baoyachi/sha256-rs#4]
Open source software should have a license declaration file.
Such as:
* Apache License, Version 2.0, [LICENSE-APACHE], <http://www.apache.org/licenses/LICENSE-2.0>
* MIT license, [LICENSE-MIT],  <http://opensource.org/licenses/MIT>

Hope to add the license declaration file. 
@baoyachi

**Comment by baoyachi** [comment]
Thx
