### ISSUE TITLE
The speed of calculating in rust seems like not as fast as in Node.

### ISSUE THREAD

**Issue by XLearner** [baoyachi/sha256-rs#9]
Hi Maintainer, I wanted to use the SHA-256 to do "Proof of Work" with rust and transformed Rust code to "WebAssembly" for the web page finally. So I did some tests separately in Node and rust. However, the result is unsatisfying. Node is much faster than Rust. I am curious about what reason could be leading to the disparity in the speed? 

Here is my testing code:

[demo-node.txt](https://github.com/baoyachi/sha256-rs/files/10810896/demo-node.txt)

[demo-rs.txt](https://github.com/baoyachi/sha256-rs/files/10810912/demo-rs.txt)

**Comment by baoyachi** [comment]
Sorry, the current performance of sha2 is really poor. I need to study the problem carefully.

**Comment by XLearner** [comment]
您好，你发送的信息我已成功接收，我会尽快回复您。Lambert Yim

**Comment by baoyachi** [comment]
Currently,new version published, please use `try_async_openssl_digest` function test it.
```toml
sha256 = "1.2.0"
```
